version: "3.9"
services:
 client-react-nginx:
    image: client-react-nginxuop
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    ports:
      - 80:8080
    restart: unless-stopped