services:
  matforum.apigateway:
    image: ${DOCKER_REGISTRY-}matforumapigateway
    build:
      context: .
      dockerfile: src/ApiGateway/MatForum.ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    depends_on:
      postgres:
        condition: service_healthy  # Add this!
      user-service:
        condition: service_started
      question-service:
        condition: service_started
      voting-service:
        condition: service_started
      identityserver-service:
        condition: service_started
      answer-service:
        condition: service_started
  postgres:
    image: postgres:15
    container_name: matforum-postgres
    environment:
      - POSTGRES_DB=matforum
      - POSTGRES_USER=matforum_user
      - POSTGRES_PASSWORD=matforum_password
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U matforum_user -d matforum"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: .
      dockerfile: src/Services/UserManagement/MatForum.UserManagement.API/Dockerfile
    container_name: user-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=matforum;Username=matforum_user;Password=matforum_password
    ports:
      - "5001:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    
  question-service:
    build:
      context: .
      dockerfile: src/Services/ForumQuestion/MatForum.ForumQuestion.API/Dockerfile
    container_name: question-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=matforum;Username=matforum_user;Password=matforum_password
    ports:
      - "5002:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
  
  voting-service:
    build:
      context: .
      dockerfile: src/Services/Voting/MatForum.Voting.API/Dockerfile
    container_name: voting-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=matforum;Username=matforum_user;Password=matforum_password
    ports:
      - "5003:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    
  answer-service:
    build:
      context: .
      dockerfile: src/Services/QuestionAnswer/MatForum.QuestionAnswer.API/Dockerfile
    container_name: answer-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=matforum;Username=matforum_user;Password=matforum_password
    ports:
      - "5004:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  identityserver-service:
    build:
      context: .
      dockerfile: src/Security/MatForum.IdentityServer.API/Dockerfile
    container_name: identityserver-service
    environment:    
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=matforum;Username=matforum_user;Password=matforum_password
    ports:
      - "5005:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data:
