version: '3.8'

services:
  user-service:
    build:
      context: ..
      dockerfile: src/Services/User/MatForum.User.API/Dockerfile
    container_name: matforum-user-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5001:80"
    restart: on-failure